### ISSUE TITLE
Custom Music not working.

### ISSUE THREAD

**Issue by UnderYouFive** [JetBoom/zombiesurvival#103]
I have tried changing the music code in sh_options.lua but my custom music doesn't play. I have tried both .mp3 and .ogg at 22000hz

**Comment by BClark09** [comment]
What have you changed it to, and what is the full path of the sound file?

**Comment by UnderYouFive** [comment]
sound/zombiesurvival/mysong.ogg

**Comment by BClark09** [comment]
I want the FULL line, and FULL path.

**Comment by UnderYouFive** [comment]
sh_options- GM.LastHumanSound = Sound("sound/zombiesurvival/lasthuman2.ogg")

Full path- garrysmod/gamemodes/zombiesurvival/content/sound/zombiesurvival/lasthuman2.ogg

**Comment by BClark09** [comment]
Works fine for me, the sample rate should be 44100Hz not 22000Hz

**Comment by UnderYouFive** [comment]
Will it not play if it is at 22000Hz?

**Comment by JetBoom** [comment]
sh_options- GM.LastHumanSound = Sound("zombiesurvival/lasthuman2.ogg")
