### ISSUE TITLE
Boss zombies are not spawning.

### ISSUE THREAD

**Issue by UnderYouFive** [JetBoom/zombiesurvival#104]
After I updated the gamemode today Boss zombies are not spawning. There are no errors. The rest of the gamemode seems to work fine.

**Comment by Zverina** [comment]
It is possible that your boss limit is set to 16 players.

**Comment by DracTheGreat** [comment]
In sh_globals you can change it back to 10

**Comment by UnderYouFive** [comment]
Yes, it was set to 16. Thank you. :)
