### ISSUE TITLE
[Question / Request - Source SDK] prop_weapon pickupcounter

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#106]
I love this idea of being able to pick up a weapon multiple times, but not so much that it has infinite pickups (or so I understand).

Looking into the FGD and the keyvalues in Hammer, I do not see anything as far as an actual limit to how many times the weapon can be picked up. I do see the NeverRemove keyvalue, but that seems to be either infinite or one time.

Am I missing something or is there simply no such thing? And if there is not, could there be (set the limit of pickups to 4, for example)

--Edit
Forgot to mention that I also spotted the maxpickupcounter in the description of the Ignore Pickup Counter keyvalue, but no actual maxpickupcounter keyvalue or input.

**Comment by BClark09** [comment]
The above change is more useful to you. The "Ignore Pickup Counter" uses the entity "logic_pickups".

**Comment by Zverina** [comment]
I should have figured it meant logic_pickups... I assumed not at first because of the name pickupcounter not being the exact same as pickups... Heh.

Anyways, I think I figured out a way to make a sort of way for a max number of pickups a gun can take (like L4D) using math_counter and logic_pickupdrop. Or am I still missing something?

I want to avoid using logic_pickups in the specific map for this situation is why I mention all of this.
