### ISSUE TITLE
[Request - Source SDK] logic_pickups + prop_weapon

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#109]
I ask for a lot. I know.

I feel this would be a useful addition to logic_pickups. An input that resets everyone's (or the caller's) current value to 0.

So, for example, Player X picked up 2/2 weapons. He cannot pick up anything else from the map. However, when the next wave begins, his counter is reset to 0/2 and he can continue to pick up weapons.

____________________________________________________________________________________

As for prop_weapon, a flag for Start Constrained would be appreciated (weapon_zs_* has it, prop_weapon does not)

**Comment by BClark09** [comment]
It'd probably be better to raise the limit progressively through the map because a supermarket swee[ of free weapons sounds like a bad idea; but that's just my opinion.

Also, is there a problem with actually constraining the prop?

**Comment by Zverina** [comment]
This is what I do for one of my maps. I increase the limit, but I do not want people who did not pick something up before to be able to pick up a bunch of stuff this time around compared to somebody who already did pick something up.

(on zs_test_facility, survivors can pick up one gun + ammo box. This later increases to two guns + two ammo boxes for the wave 3 guns, I do not like the fact that some survivors can pick up two guns and boxes if they happened to wait).


I suppose I could squeeze a gun in to where I want it using a physics clip or similar, but prop_weapon does not have the constrained flag.
Unless it is possible to add flags in yourself that I am not aware of?

**Comment by BClark09** [comment]
https://developer.valvesoftware.com/wiki/Phys_constraint

**Comment by Zverina** [comment]
Oooh, I have not noticed that entity before.

Thanks for pointing it out.
