### ISSUE TITLE
[Source SDK] point_zsmessage issue

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#111]
It appears using a comma in the message input will... break any future messages triggered in the same logic_relay.

For example..

"This text would be okay."
"But, using this would cause problems"

When you use a comma, any characters after it are chopped and removed.

I suppose this is sort of an obvious thing since some coding uses a comma to separate values and whatnot, but I was hoping there was a way to fix this issue. Incorrect grammar on something official bugs the hell out of me.

--EDIT--
It appears that after / during compiling, the messages get chopped in the logic_relay. Closing and reopening the .vmf is when the text is chopped. The delay is also reset to 0.

**Comment by BClark09** [comment]
For documentation's sake, commas cant be entered into string inputs in hammer. To get around this, use custommessage with string02 keyvalue set as a comma and then the following combination.

setstring01 'the bit before the comma'
setstring03 'the bit after the comma'
displaystrings
