### ISSUE TITLE
Override GM:VehicleMove

### ISSUE THREAD

**Issue by DracTheGreat** [JetBoom/zombiesurvival#112]
On maps with vehicles (zs_lost_isle is the best one I can think of), using the scroll wheel in the vehicle produces script errors that can eventually crash the client.

Override GM:VehicleMove (the base gamemode function) so it's not calling something that doesn't exist please.

**Comment by BClark09** [comment]
There shouldn't really be vehicles in Zombie Survival anyway.

**Comment by DracTheGreat** [comment]
There shouldn't, but there are in some maps. Whatever.
