### ISSUE TITLE
Mechanic's Wrench Does Not Repair Boards (Aegis)

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#115]
I am not even totally sure if this is an intentional mechanic, but I recall repairing boards in the past with a wrench.

Anyways, I quickly packed up a nearly-broken board while it was being attacked in order to save and repair it later.

Later, I placed it in a safe place and started smacking it with a wrench with no luck. Point floaters came out (as if I was damaging it), but no actual repairs.

**Comment by JetBoom** [comment]
This is intended. Otherwise we'd have barricades with infinite health.

**Comment by Zverina** [comment]
Well, the way it seemed to be in the past (when I was able to repair it on a default server...?), you could only repair it when it was not taking damage, similar to a turret.

But mkay, good to know.
