### ISSUE TITLE
Next Wave in 00:00

### ISSUE THREAD

**Issue by UnderYouFive** [JetBoom/zombiesurvival#124]
Anyone else have this problem? I striped my server of all it's addons and put the latest ZS Gamemode on it. And when wave 1 should begin I just get "Next Wave in 00:00" flashing. (This happens every game)

http://i.imgur.com/cHaBotb.jpg

**Comment by Seba0702** [comment]
I have the same problem!

**Comment by JetBoom** [comment]
Can't replicate.

**Comment by UnderYouFive** [comment]
@Seba0702, 
Do you have any addons on your server?

**Comment by Zverina** [comment]
If anything, it may be a result of not having any zombies, but there have been multiple times where the gamemode... broke and this, or some other weird thing, happened. Sometimes, props could not be carried, zombies would not respawn, or this. I have never been able to replicate it, though.

**Comment by UnderYouFive** [comment]
I'll try with another player to see if only having one player makes this happen.

**Comment by ForrestMarkX** [comment]
Need the server log cause this only happens if any of the functions that sets the wave fails to run due to errors

**Comment by UnderYouFive** [comment]
I have not gotten any errors from the gamemode.

**Comment by JetBoom** [comment]
Number of waves convar might be set to 0.

**Comment by Seba0702** [comment]
@UnderYouFive Yes i got addons, but i removed them 1 by one to check wich one made the problem, apperantly non of them..

**Comment by Seba0702** [comment]
Mine do change waves, and it does count down time to time after it have count 00:00 for a long time. Everytime the timer reach 00:00 it keeps being that for a good amount of time before starting again, for the new wave. Even tho the timer is flashing zombie do spawn when the wave starts, but it still says, you are dead. But you can respawn

**Comment by UnderYouFive** [comment]
Nope, 03/27/2015 - 03:41:14: server_cvar: "zs_numberofwaves" "6"

**Comment by Seba0702** [comment]
@UnderYouFive  What addons do you have?? PLZ list the all, so we can compare.

**Comment by UnderYouFive** [comment]
@Seba0702, I removed all of my addons, and I still get this problem.

**Comment by Seba0702** [comment]
@UnderYouFive It must be the gamemode.

**Comment by JetBoom** [comment]
If it works fine for everyone but two people I doubt it.

**Comment by Seba0702** [comment]
@JetBoom i already redownloaded the gamemode, but same problem

**Comment by Seba0702** [comment]
@JetBoom Where are the files for the Timer, then? So i can look if there are any mistake made by me.

**Comment by Seba0702** [comment]
@UnderYouFive What host do u have?

**Comment by BClark09** [comment]
Your servers need updating to include a recent hotfix. Clients aren't able to use the GetGlobalFloat function to retrieve the wave timer.

**Comment by Seba0702** [comment]
@BClark09 Thanks!!! I fucking love you.

**Comment by UnderYouFive** [comment]
Bam! My server is now updated! Thanks a lot BClark09!
