### ISSUE TITLE
Hammer Bug - Cannot Use At All

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#132]
So, I have noticed since playing a bit of ZS recently that after you run out of nails, the hammer bugs out and cannot be used at all (until you somehow acquire more nails via drops or arsenal). 

Once you run out of nails, you cannot attack, repair, or remove placed nails with the hammer. I assume this is a result of the Gmod update a few weeks ago, though I am surprised it has not been fixed yet (or noticed, at least).

**Comment by Zverina** [comment]
As a side note, it seems that pistols (and maybe all weapons) cannot just be resupplied and reloaded right away, as you have to switch weapons and back to it after you have gotten the ammo. I assume the bug is the same.

**Comment by JetBoom** [comment]
Most likely will have to go back to having a dummy ammo as secondary ammo type.
