### ISSUE TITLE
[Request] Ability to change worth

### ISSUE THREAD

**Issue by RyanMonkey** [JetBoom/zombiesurvival#133]
Hi,

Would it be possible to add the ability to change the starting worth?
Something like that or some information into the direction I would need to take to make this possible would be fantastic.

Thanks!

Edit: Found it.

**Comment by BClark09** [comment]
You mentioned before your edit that you intended to give different worth to admins and VIPs, I'm guessing they pay for that privilege?

**Comment by RyanMonkey** [comment]
Yeah, I forgot about the license. I'm not going to do that.

I found out how to change worth.
