### ISSUE TITLE
GetMaxHealth()

### ISSUE THREAD

**Issue by Seba0702** [JetBoom/zombiesurvival#134]
Do so the health % under a player/zombie is by GetMaxHealth() and not the zombies base health. This is so we can install addons to boost there health through perks and stuff like that. C:

**Comment by JetBoom** [comment]
no.

**Comment by Zverina** [comment]
So, low-HP traits for zombies?
Nah...
If anything, just make your own new zombies, but all, or most at least, of the current ones would OP. 

And I am assuming you do not mean perks as in donator-specific traits. Those are poop. And not allowed, if I remember correctly.
