### ISSUE TITLE
Possible butcher related crash

### ISSUE THREAD

**Issue by UnderYouFive** [JetBoom/zombiesurvival#136]
At least on my server, if someone attacks the butcher or uses the butcher knife they will crash. Now I will say it again, I HAVE NOT edited the butchers files. Anyone else get this problem? Could it be related to the "07.02.15" Garry's Mod update?

**Comment by DracTheGreat** [comment]
can't confirm.

**Comment by Mka0207** [comment]
It might be client side for whomever it affects, you can try having them "clean" their garry's mod of addon's custom content that might very well be overwriting important files.

Easy way to clean garry's mod : https://www.youtube.com/watch?v=ugoLiZjSgPg

**Comment by UnderYouFive** [comment]
Yeah, but this is pretty much everyone from what I have seen.

**Comment by BClark09** [comment]
I haven't be able to replicate this.
