### ISSUE TITLE
logic_winlose Custom Camera Issue

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#138]
Part of it was already solved by Benjy, the humans winning would not go to the custom camera location, however, there is one more that I have found.

If a vector is specified for the camera, but the custom camera option is disabled, the usual camera-jumping-to-last-dead-human does not occur while slow-motion does.

**Comment by JetBoom** [comment]
Fixed in feb2016 update.

For the future: It's not a "custom camera" option. It's a "camera at all" option. If you want to disable the custom location then set it to 0 0 0.
