### ISSUE TITLE
logic_infliction Looping

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#139]
Similar to the old issue I had with the OnLastHuman input looping, OnInflictionReached has the same result.

It was changed so that whatever inputs would occur on OnLastHuman only occur once (what I wanted); I would like this to be the same for OnInflictionReached.

**Comment by Zverina** [comment]
I have found a small workaround for what I needed on this. 

What I wanted was to unlock a Wraith at the 25% mark. I originally tried using OnInflictionReached to trigger a point_zsmessage and let everyone know the Wraith was unlocked, but it would constantly repeat this message.

What I did to avoid this was use a separate logic_classunlock entity and use the OnClassUnlocked input to trigger the point_zsmessage instead.

However, I still feel like giving the same solution that OnLastHuman got for OnInflictionReached would be helpful.

**Comment by JetBoom** [comment]
fixed in feb2016
