### ISSUE TITLE
Boss Butcher Disconnect.

### ISSUE THREAD

**Issue by C0nw0nk** [JetBoom/zombiesurvival#147]
So i noticed when players leave the server they drop their weapons on the floor.

If The Butcher disconnects this does not happen i am not sure if it is intentional or not.

Perhaps adding at the end of the butcher file.
https://github.com/JetBoom/zombiesurvival/blob/master/gamemodes/zombiesurvival/gamemode/zombieclasses/boss_butcher.lua#L149

local function DropWeapon(pl)
    local pos = pl:GetPos()
    timer.Simple(0, function()
        MakeButcherKnife(pos)
    end)
end
hook.Add("PlayerDisconnected", "DropWeapon.ButcherDisconnected", DropWeapon)

**Comment by BClark09** [comment]
Only the butcher can butch.
