### ISSUE TITLE
GM.WaveOneZombies not changing.

### ISSUE THREAD

**Issue by Novus-SB** [JetBoom/zombiesurvival#149]
In the GM.WaveOneZombies line, you can change this to a lower, or higher amount, however it will not make any difference to how many zombies are selected when the game starts, this will also always cap at 5 players. This causes issues with servers above 50 population, as 5 zombies forced against 50 humans, you can imagine the balance tilts obviously in one side's favor.

I have tried this on both a fresh install and current status install on my test server.

Reference:

https://github.com/JetBoom/zombiesurvival/blob/master/gamemodes/zombiesurvival/gamemode/sh_options.lua#L322

**Comment by JetBoom** [comment]
Fixed in feb2016
