### ISSUE TITLE
Adding Weapons Issue

### ISSUE THREAD

**Issue by Aceman9622** [JetBoom/zombiesurvival#152]
When I add the lines:

GM:AddPointShopItem("ots33", "OTs-33 Pernach", nil, ITEMCAT_GUNS, 30, "fas2_ots33")
GM:AddPointShopItem("uzi", "IMI Uzi", nil, ITEMCAT_GUNS, 35, "fas2_uzi")
GM:AddPointShopItem("mp5a5", "MP5A5", nil, ITEMCAT_GUNS, 40, "fas2_mp5a5")
GM:AddPointShopItem("mp5sd6", "MP5SD6", nil, ITEMCAT_GUNS, 45, "fas2_mp5sd6")

GM:AddPointShopItem("mac11", "M11A1", nil, ITEMCAT_GUNS, 55, "fas2_mac11")

It will not work.

The only thing that occurs are these errors..

--------- ---------

[ERROR] gamemodes/zombiesurvival/gamemode/vgui/ppointshop.lua:225: attempt to index field 'Entity' (a nil value)

OpenPointsShop - gamemodes/zombiesurvival/gamemode/vgui/ppointshop.lua:225
unknown - LuaCmd:1

[ERROR] gamemodes/zombiesurvival/gamemode/vgui/ppointshop.lua:91: attempt to index field 'm_NameLabel' (a nil value)

unknown - gamemodes/zombiesurvival/gamemode/vgui/ppointshop.lua:91

--------- ---------

I'm not sure what is wrong.

Is the format wrong?

GM:AddPointShopItem("random name", "Weapon Name In-game", nil, ITEMCAT_GUNS, price, "weaponfile") ????????????

**Comment by Aceman9622** [comment]
Also, it will open and close the aresnal really quickly. It will just show the error once and not work.  The only weapons that will work are the ots, uzi, mp5a5, and mp5sd6, but anything below it will not work resulting the error.

**Comment by JetBoom** [comment]
not for 3rd party addons.
