### ISSUE TITLE
RestartGesture bug on weapons

### ISSUE THREAD

**Issue by poseidonservers** [JetBoom/zombiesurvival#159]
[ERROR] gamemodes/zombiesurvival/entities/weapons/weapon_zs_blaster.lua:51: attempt to call method 'RestartGesture' (a nil value)
  1. unknown - gamemodes/zombiesurvival/entities/weapons/weapon_zs_blaster.lua:51

Happens when reloading weapons

**Comment by JetBoom** [comment]
https://github.com/JetBoom/zombiesurvival/commit/dae0b072c6bb27dd3cde2def7fb4ed1f1ab0a043

It's a temp fix until I get around to full pushing from nox.
