### ISSUE TITLE
Pendboard 'DList' Error Fix

### ISSUE THREAD

**Issue by Mka0207** [JetBoom/zombiesurvival#163]
I know this error has been around for quite sometime so here is how I fixed it.

In gamemode/vgui/pendboard.lua, AddHonorableMention calls when the panel is created but for late joiners the panel list seems to return nil so I added a check around line 7 : 

`if !pEndBoard.List then return end`

Then to prevent 'heading' and 'subheading' from returning nil, I changed line 34 and 45 to : 

`local heading = EasyLabel(frame, "", "ZSHUDFont", COLOR_GREEN)`

`local subheading = EasyLabel(frame, "", "ZSHUDFont", COLOR_GREEN)`

Once all of that is done the error will be fixed.

**Comment by JetBoom** [comment]
I've never heard of this.
```
if not (pEndBoard and pEndBoard:IsValid()) then
	MakepEndBoard(ROUNDWINNER)
end
```
Maybe because I'm using :IsValid() instead of :Valid() which is deprecated?

> Then to prevent 'heading' and 'subheading' from returning nil
They can't return anything and they are impossible to be nil.

**Comment by Mka0207** [comment]
Basically if a player joins late after the game has ended and the pendboard list is filled with honorable mentions during that session it will spit out an error and bug out the HUD, adding the DList check fixed it but then heading and subheading didn't have a fallback. An yeah a panel :Valid() check might work too, it's just an annoying bug to recreate.

**Comment by JetBoom** [comment]
> An yeah a panel :Valid() check might work too

uhhhhh

> heading and subheading didn't have a fallback

They didn't need one. There's no fallback required. it's either A or B, not A or B or nil

**Comment by Mka0207** [comment]
rip.
