### ISSUE TITLE
a little problem in the screen

### ISSUE THREAD

**Issue by sulfito** [JetBoom/zombiesurvival#165]
hi, after the last update of gmod, im having this problem, its not a big problem, but anyways i want to ask for some help to fix it

http://images.akamai.steamusercontent.com/ugc/298734165336690241/DDDF5D2DB9FAD8859635F7E88985C10696719376/

this is when a player will be the boss, idk why this happens, this happens to some players, not all of them in the server.

http://images.akamai.steamusercontent.com/ugc/298734165340300629/EA20AF962FE0ABC1C977252A31E1B7B70F61D6FA/

this happens after the last update too, for what i know, this happens only to me, so maybe its a problem in my gmod.

http://images.akamai.steamusercontent.com/ugc/298734165340301017/3793D26DC73DF5E86E872D57CBE6D261FE430634/

and finally this one, its like the problem with the health display, anyways, i dont know almost nothing of lua or script, so if u can help me telling me what i need to do to fix it will be great.

thx for ur time

**Comment by Intificial** [comment]
1. Missing translation in one the files and will only happen to those with a certain language, seems to be spanish.
2. What are you showing in this?
3. It's to do with text alignment due to a GMod update. This will get fixed in the near future.

**Comment by sulfito** [comment]
1. well, the first one i already fix it, the translation to spanish its incomplete, so i make a new one.
2. the second picture, if u can see in the desert deagle, the type of numbers in the hud (ammo and bullets) but i think thats my problem only.
3. and, well then i need to wait

thx for the help n_n

**Comment by Intificial** [comment]
Second picture still looks fine to me.
