### ISSUE TITLE
[Suggestion] Muscular door change

### ISSUE THREAD

**Issue by orecros** [JetBoom/zombiesurvival#169]
At the moment, when you pick up a prop with muscular, the prop is centered on the same point every time. I'm assuming it's the origin, but I haven't had a chance to check. Would fix issues with doors if props centered on the point where you pressed E on them instead. Could be specific to certain props (doors included, of course). Possible issues with prop surfing.

**Comment by JShorthouse** [comment]
Has anyone made a fix for this yet? Tried altering the status_human_holding entity but couldn't get doors to be held properly.

All that needs to be changed is for doors to use the center of the model as their origin rather than the hinge point.

**Comment by JShorthouse** [comment]
https://github.com/Dadido3/zombiesurvival/commit/28cdc6621af7094cd73779b4aad611f5848a341c
