### ISSUE TITLE
Problem with changing the font

### ISSUE THREAD

**Issue by kradosser** [JetBoom/zombiesurvival#180]
I was trying to change the font on cl_init.lua line 868 `local fontfamily = "Typenoksidi"` to an different font, but it always show the font "Arial" without any notes in the logs.
Yes i already added the .ttf File to my FastDL `resource.AddFile( "materials/fonts/font.ttf" )`
Greetings, 
Kradosser.

**Comment by JetBoom** [comment]
This isn't what github is for.
