### ISSUE TITLE
Map will change after 1 round even when I set zs_roundlimit to 4

### ISSUE THREAD

**Issue by Krejzifik** [JetBoom/zombiesurvival#188]
As the title says map will change after 1 round even when I set zs_roundlimit to 4.
I've set the zs_roundlimit 4 in server.cfg and autoexec.cfg

**Comment by Yushe** [comment]
https://github.com/JetBoom/zombiesurvival/blob/f6e92a3ef73e2e10c51bf7e6c2d2e40548905f29/gamemodes/zombiesurvival/gamemode/sh_options.lua#L352

**Comment by Krejzifik** [comment]
@Yushe Do you know what server.cfg or autoexec.cfg are? They set convars after the server starts or change map.

**Comment by Yushe** [comment]
Your meant to use that file for zs configs not those.

**Comment by Krejzifik** [comment]
@Yushe Ok, but still even if it is set to 3 the map changes after 1 round

**Comment by Yushe** [comment]
Do you have a vote map addon? It might conflict with zs.

**Comment by Krejzifik** [comment]
@Yushe Yeah, but it doesn't show up. So I thought it doesn't work.
I'll delete it and see if it'll help

**Comment by Krejzifik** [comment]
@Yushe Nope, map still changes after 1 round.

**Comment by XGenyNL** [comment]
@Krejzifik There is also something that has to do with the the **time**. For example, script: change the map when 3 rounds have been played OR 15 minutes of time passed. Make sure you also edit that.

**Comment by Krejzifik** [comment]
@XGenyNL This isn't possible as I die as round begins (around 2 minutes)

**Comment by JetBoom** [comment]
zs_timelimit has to be set as well.
