### ISSUE TITLE
Self Redeem

### ISSUE THREAD

**Issue by Hitmare** [JetBoom/zombiesurvival#223]
Hello

How can i enable Self Redeem?

`zs_playerredeemed 1
Unknown command "zs_playerredeemed"`

BR 
Hitmare

**Comment by arthurgeron** [comment]
`zs_playerredeemed` It's a internal network string not an actual command. Players should be able to redeem after eating 4 brains unless they've chosen not to through their own personal in-game options, I believe that's your question right?

**Comment by Blueberryy** [comment]
This command included in D3bots addon
