### ISSUE TITLE
Humans can damage nailed props via melee attack

### ISSUE THREAD

**Issue by BoXiousNet** [JetBoom/zombiesurvival#23]
Tested just now on the server
Using a plank and repeatedly hitting a nailed prop, will eventually cause it to lose hp.

**Comment by JetBoom** [comment]
Bumping this now that I'm going over old issues. I remember trying this. I set +attack and host_timescale to 10 with a plank on a nailed prop in my own server. Went afk for about an hour, came back and nothing out of the ordinary happened. It's a small issue so oh well.
