### ISSUE TITLE
Move all text files to new `data_static` folder

### ISSUE THREAD

**Issue by FlorianLeChat** [JetBoom/zombiesurvival#249]
Since the last Garry's Mod update, all addons with a `data` folder inside no longer work because these static files have to be moved to a special (read-only) folder called `data_static`. I've reported this issue to the Garry's Mod developers (https://discord.com/channels/565105920414318602/589120351238225940/1185530854278189106) but it's not a bug and is considered a new behavior. Several gamemodes including [Murder](https://github.com/MechanicalMind/murder/issues/88), [MelonBomber](https://github.com/MechanicalMind/melonbomber/issues/9) and [Morbus](https://github.com/Remscar/Morbus/issues/51) are suffering from the same issue.

**Comment by JetBoom** [comment]
I updated the addon to use data_static and that doesn't do anything.

"File not on whitelist: gamemodes/zombiesurvival/content/data_static/zsmaps/cs_sprint_trading.txt"

Downloading directly from github works, I don't care enough to try and fix gmod addons beyond what I've already done. Complain to the gmod devs.

**Comment by FlorianLeChat** [comment]
> Downloading directly from github works, I don't care enough to try and fix gmod addons beyond what I've already done. Complain to the gmod devs.

![image](https://github.com/JetBoom/zombiesurvival/assets/26360935/9fe92db8-dc26-4bb6-8de7-00d73138e561)

From what I can tell, this change only applies to GMA files, downloading the gamemode from GitHub or extracting it "fixes" this issue.

> I updated the addon to use data_static and that doesn't do anything.
> 
> "File not on whitelist: gamemodes/zombiesurvival/content/data_static/zsmaps/cs_sprint_trading.txt"

I can also confirm this on my dedicated server, but I'm suspect that this `data_static` folder must be created at the root of the gamemode directory instead of `content/data` like the Jazztronauts developers did, Lua scripts seem to require some adaptation too, unfortunately...

- https://github.com/Foohy/jazztronauts/commit/b2faa2dac8ee84dbf45b1fa86ba4b148ff43dded
- https://github.com/Foohy/jazztronauts

**Comment by JetBoom** [comment]
I've deleted the data folder when uploading it to workshop. The files aren't absolutely critical.
