### ISSUE TITLE
Possible Meat-Hook Related Crash

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#62]
![pcrash](https://cloud.githubusercontent.com/assets/9141783/5448145/cc626630-848e-11e4-968c-654bddb0e414.png)
This occurred when a zombie was hit by a meat-hook, then several moments later turned into a torso and died (in to an explosion from shotgun headshot). The server locked up (crashed) a second later.

**Comment by JetBoom** [comment]
Fixed in feb2016 update.
