### ISSUE TITLE
Grenade-Related Error

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#74]
![nades](https://cloud.githubusercontent.com/assets/9141783/5523816/233ebc0e-8982-11e4-95a7-02ea0238b7db.png)
This wall of blue text popped up while my server was hosting the current version of zs_gauntlet_reborn_v9 (12/22/14)

I feel as if it is just something that the map did due to some coding mistake (because of those neat-looking spells), but I figured I should place it here just in case.

**Comment by JetBoom** [comment]
Fixed in feb2016
