### ISSUE TITLE
Changing Zombie Class Bug

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#86]
From what I was able to gather from this happening once earlier, if a zombie took enough damage to be turned into a torso (still a normal zombie, but ready to turn into torso on death), and that zombie changes classes, he becomes a torso.

This may also happen with legs, though I am unsure. I will attempt to replicate this soon.

**Comment by Zverina** [comment]
Did not get a screenshot or anything, but it occurred (when slaying a zombie).

So, yeah, replicatable. Not huge, but a small annoyance at times.

**Comment by DracTheGreat** [comment]
It's because the zombie class death hook is still called for suicide. The code in it that turns you in to a torso should check for that. The line in gamemode/zombieclasses/zombie.lua(CLASS:ReviveCallback) should be changed from:

```
if not pl.Revive and not dmginfo:GetInflictor().IsMelee and not dmginfo:GetInflictor().NoReviveFromKills and dmginfo:GetDamageType() ~= DMG_BLAST and dmginfo:GetDamageType() ~= DMG_BURN and (pl:LastHitGroup() == HITGROUP_LEFTLEG or pl:LastHitGroup() == HITGROUP_RIGHTLEG) then
```

to:

```
if pl ~= attacker and not pl.Revive and not dmginfo:GetInflictor().IsMelee and not dmginfo:GetInflictor().NoReviveFromKills and dmginfo:GetDamageType() ~= DMG_BLAST and dmginfo:GetDamageType() ~= DMG_BURN and (pl:LastHitGroup() == HITGROUP_LEFTLEG or pl:LastHitGroup() == HITGROUP_RIGHTLEG) then

That should fix it.

**Comment by JetBoom** [comment]
That's already checked for.

````
if attacker:IsValid() and attacker:IsPlayer() and attacker ~= pl then
			if classtable.Revives and not pl.Gibbed and not headshot then
				if classtable.ReviveCallback then
					revive = classtable:ReviveCallback(pl, attacker, dmginfo)
````

**Comment by DracTheGreat** [comment]
Ah, alright, sorry.
