### ISSUE TITLE
point_propnocollide error (another)

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#91]
![untitled](https://cloud.githubusercontent.com/assets/9141783/5591727/62b5216a-9135-11e4-8dc0-bace47eafd0d.png)
Appeared in the console. I was not in-game at the time. Most up-to-date version, not including forcepickup commits.

**Comment by JetBoom** [comment]
81820d6e8b767d4a88e7902f43e72144845bd640
