### ISSUE TITLE
Fading Medkit Aura

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#95]
In a way. 

Survivors will lose their aura and simply stay normal and.. aura-less.

I am not totally sure what causes it, but I believe that as soon as all survivors are out of your aura range is when it occurs.

So, if a survivor in still in your range, everyone will still glow as intended, but if you run away from everyone /while/ the medkit is out, then run back towards them, they will not regain their auras (until you put away and take out the medkit again).

**Comment by Seba0702** [comment]
I can confirm this
