### ISSUE TITLE
obj_player_extend error ( Player is NULL(!?) )

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#96]
Lua Error: [ERROR] gamemodes/zombiesurvival/gamemode/obj_player_extend.lua:584: Player is NULL(!?) 
1. GetObserverMode - [C]:-1 
2. Alive - gamemodes/zombiesurvival/gamemode/obj_player_extend.lua:584 
3. DoTouch - gamemodes/zombiesurvival/entities/entities/trigger_zombieclass/init.lua:68
4. unknown - gamemodes/zombiesurvival/entities/entities/trigger_zombieclass/init.lua:109

My apologies if it looks a little weird, new server host, rcon tool is weird.

**Comment by JetBoom** [comment]
Can't do anything about it, doesn't do anything bad anyway.
