### ISSUE TITLE
gamemode/init.lua error

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#97]
Lua Error: [ERROR] gamemodes/zombiesurvival/gamemode/init.lua:794: attempt to call method 'IsValid' (a nil value) 
1. unknown - gamemodes/zombiesurvival/gamemode/init.lua:794 
2. Spawn - [C]:-1 
3. UnSpectateAndSpawn - gamemodes/zombiesurvival/gamemode/obj_player_extend_sv.lua:429 
4. SecondWind - gamemodes/zombiesurvival/gamemode/obj_player_extend_sv.lua:441 
5. unknown - gamemodes/zombiesurvival/entities/entities/status_revive_slump_human/init.lua:14

I was sitting (not lying) down in the zombie spawn, AFK for a bit, when this error popped up.
'tis all.

**Comment by JetBoom** [comment]
These errors with passed engine arguments not even having an IsValid member on them are dumb. We shouldn't have to check
````
if ent and type(ent) == "Entity" and ent.IsValid and ent:IsValid()
````
