### ISSUE TITLE
gamemode/shared error

### ISSUE THREAD

**Issue by Zverina** [JetBoom/zombiesurvival#99]
Lua Error: [ERROR] gamemodes/zombiesurvival/gamemode/shared.lua:431: attempt to call method 'Team' (a nil value) 
1. unknown - gamemodes/zombiesurvival/gamemode/shared.lua:431

When a player died (small server, 3 players messing around), the survivor never switched to zombie or got up. Gamemode essentially "broke," I guess.

**Comment by DracTheGreat** [comment]
+1 

I've seen this happen on a huge amount of servers.

**Comment by JetBoom** [comment]
````
420 GM:PlayerCanHearPlayersVoice(listener, talker)
431 return listener:Team() == talker:Team()
````

Is that right? Stupid that engine functions are called on invalid players.
